name: 0.0.2. Lazy - Institutions - With real wallet

on: 
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Environment base URL to run the tests on.'
        type: string
        default: 'https://institutions.staging.summer.fi'
        required: true

jobs:
  institutions-real-wallet-tests:
    uses: ./.github/workflows/z_Reusable_InstitutionsWithRealWallet.yml
    with:
      base_url: ${{ inputs.base_url }}
      script: ci:institutions-with-real-wallet
    secrets: inherit
